### ISSUE TITLE
Pass namespace in separate flags while necessary

### ISSUE THREAD

**Issue by mirshahriar** [appscode/chartify#10]
Example:
Do not pass `<secret-name>.<namespace>` in `--secrets` flag

Only service name can take `<namespace>` after it.

**Comment by tamalsaha** [comment]
I am afraid this will result in a explosion of flags. :(

**Comment by mirshahriar** [comment]
May be use some other symbol like "@" which is not allowed in name to separate from namespace. Then need to explain that in flag description.

**Comment by tamalsaha** [comment]
The kube identifier rules are: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/identifiers.md

I think using `@` as separator will work.
