### ISSUE TITLE
Flag input parameter to preserve resources name in output

### ISSUE THREAD

**Issue by yadavnikhil** [appscode/chartify#33]
Can we have some flag to pass to Chartify, which can bypass name change for resources?

Ex. 
--preserve-name true - will not change resources name in output. will be same as input.
It will solve most of the scenarios when working with secret combinations & local registry.

**Comment by tamalsaha** [comment]
Are you saying that no resource names will be changed?

**Comment by yadavnikhil** [comment]
yes, only for ObjectMeta.Name in generateObjectMetaTemplate(). This way, i can sync & control all names in my Charts. Its on demand, default will be existing logic.

**Comment by tamalsaha** [comment]
I think this sounds reasonable. Want to send a pr?
