### ISSUE TITLE
Add Support for HorizontalPodAutoscaler

### ISSUE THREAD

**Issue by cnighojkar** [appscode/chartify#42]
While creating helm chart for kubespec having **"HorizontalPodAutoscaler"** , getting below exception
`HorizontalPodAutoscaler is not supported. Please add manually.`

**Comment by tamalsaha** [comment]
Thanks for the feature request. Do you want to contribute this feature?

**Comment by mstrYoda** [comment]
@tamalsaha Is that feature added? If not I volunteer to contribute.

**Comment by tamalsaha** [comment]
No, this feature was not added. Please feel free to send a pr.
