### ISSUE TITLE
Deployments support

### ISSUE THREAD

**Issue by zoidyzoidzoid** [appscode/chartify#5]
We're moving to helm and it'd be useful if we could chartify our deployments. I've solved it for the mean time by using replicasets to generate the charts and then editing them.

This is an awesome project, and I'd happily try adding deployments support.

Is there a reason this hasn't been added yet?

Otherwise I'll try make a PR this weekend.

**Comment by tamalsaha** [comment]
@zoidbergwill , thanks for using Chartify. I think we missed it from the CLI. It is added to cli now https://github.com/appscode/chartify/commit/9ce1ec30a2502b6d618b4cc90a0dc094af438e0d

**Comment by zoidyzoidzoid** [comment]
Awesome, thanks! :+1:
